import { useState } from 'react';
import { Target, UserCircle, Robot, PencilSimpleLine, X, CaretDown, CheckCircle, CursorText, ArrowLeft } from '@phosphor-icons/react';
import { useNavigate } from 'react-router-dom';

function Workspace() {
  const navigate = useNavigate();
  const [foundErrors, setFoundErrors] = useState(2);
  const totalErrors = 5;
  const [selectedHighlight, setSelectedHighlight] = useState<number | null>(1);
  const [annotation, setAnnotation] = useState("");
  const [errorType, setErrorType] = useState("Logical Error");
  const [resolved, setResolved] = useState<number[]>([]);

  const handleSubmit = () => {
    if (selectedHighlight !== null && !resolved.includes(selectedHighlight)) {
      setResolved([...resolved, selectedHighlight]);
      setFoundErrors(prev => Math.min(prev + 1, totalErrors));
      setAnnotation("");
    }
    setSelectedHighlight(null);
  };

  return (
    <div className="flex flex-col h-screen bg-gray-50 font-sans overflow-hidden">
      {/* 绝对统一的高度与排版的顶部导航栏 */}
      <header className="bg-white border-b border-gray-200 px-8 h-[72px] flex justify-between items-center shrink-0 w-full z-10">
        <div className="flex items-center gap-3 w-1/3">
          <button onClick={() => navigate('/student/dashboard')} className="mr-2 text-gray-400 hover:text-violet-600 transition">
            <ArrowLeft size={24} weight="bold" />
          </button>
          <Target weight="fill" className="text-violet-600 text-3xl" />
          <h1 className="text-xl font-bold text-gray-900">Debunk AI</h1>
        </div>
        
        <div className="flex justify-center w-1/3">
          <div className="flex bg-white px-5 py-2 rounded-full border border-gray-200 shadow-sm items-center gap-4">
            <span className="text-sm font-semibold text-gray-600">Task Progress</span>
            <div className="flex gap-2 items-center">
              <div className="text-sm font-medium text-gray-700">
                You've found <span className="text-violet-600 font-bold text-lg">{foundErrors}/{totalErrors}</span> AI errors
              </div>
              <div className="w-32 h-2.5 bg-gray-100 rounded-full ml-2 overflow-hidden border border-gray-200">
                <div 
                  className="h-full bg-violet-600 transition-all duration-500 rounded-full"
                  style={{ width: `${(foundErrors / totalErrors) * 100}%` }}
                ></div>
              </div>
            </div>
          </div>
        </div>
        
        <div className="flex items-center justify-end gap-4 w-1/3">
          <UserCircle size={32} className="text-gray-400 hover:text-violet-600 cursor-pointer transition" />
        </div>
      </header>

      {/* Main Content */}
      <main className="flex flex-1 overflow-hidden">
        {/* Left Panel: Text Reading Area */}
        <section className="flex-1 overflow-y-auto w-2/3 p-12 bg-white z-0 relative">
          <div className="max-w-4xl mx-auto">
            <div className="mb-10">
              <h2 className="text-3xl font-bold text-gray-900 mb-3">A Brief History of Computer Science (AI-Generated)</h2>
              <p className="text-sm text-gray-500 flex items-center gap-2">
                <Robot size={18} /> Generated by AI Assistant. Please review and debunk the flaws.
              </p>
            </div>
            <div className="space-y-6 text-lg leading-relaxed text-gray-800">
              <p>
                The development of computer science is a process full of innovation and breakthroughs. Early calculation tools can be traced back to the ancient abacus. However, modern computers in the true sense originated in the mid-20th century.
              </p>
              <p>
                During World War II, Alan Turing proposed the concept of the "Turing Machine" and successfully cracked the German Enigma machine.{' '}
                <span 
                  className={`highlight ${selectedHighlight === 1 && !resolved.includes(1) ? 'active' : ''} ${resolved.includes(1) ? 'highlight-resolved' : ''}`}
                  onClick={() => setSelectedHighlight(1)}
                >
                  Subsequently in 1950, Turing invented the world's first personal smartphone, which greatly promoted the development of the mobile internet.
                </span>{' '}
                This feat completely changed the way humans communicate.
              </p>
              <p>
                Entering the 21st century, artificial intelligence experienced explosive growth. The breakthrough of deep learning technology relies on two factors: massive data and powerful computing capabilities.{' '}
                <span 
                  className={`highlight ${selectedHighlight === 2 && !resolved.includes(2) ? 'active' : ''} ${resolved.includes(2) ? 'highlight-resolved' : ''}`}
                  onClick={() => setSelectedHighlight(2)}
                >
                  Because the serial computing power of GPUs (Graphics Processing Units) is much lower than CPUs, deep learning training relies completely on modern high-performance CPU clusters.
                </span>{' '}
                This makes complex systems like large language models possible.
              </p>
              <p>
                In conclusion, although modern computing architectures are increasingly complex, their underlying logic still relies on the foundations laid by Turing and von Neumann over half a century ago.
              </p>
            </div>
          </div>
        </section>

        {/* Right Panel: Annotation Box */}
        <aside className="w-[450px] bg-gray-50 border-l border-gray-200 p-8 flex flex-col h-full overflow-y-auto shrink-0">
          {selectedHighlight && !resolved.includes(selectedHighlight) ? (
            <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6 flex flex-col gap-6 animate-fade-in-up">
              <div className="flex justify-between items-center border-b border-gray-100 pb-4">
                <h3 className="font-bold text-lg text-gray-900 flex items-center gap-2">
                  <PencilSimpleLine size={20} className="text-violet-600" />
                  Add Annotation
                </h3>
                <button onClick={() => setSelectedHighlight(null)} className="text-gray-400 hover:text-gray-600 transition">
                  <X size={20} />
                </button>
              </div>
              
              <div className="bg-yellow-50 text-yellow-800 text-sm p-4 rounded-xl border border-yellow-200 italic shadow-inner">
                "{selectedHighlight === 1 ? 'Subsequently in 1950, Turing invented the world\'s first personal smartphone, which greatly promoted the development of the mobile internet.' : 'Because the serial computing power of GPUs (Graphics Processing Units) is much lower than CPUs, deep learning training relies completely on modern high-performance CPU clusters.'}"
              </div>

              <div className="flex flex-col gap-2">
                <label className="text-sm font-semibold text-gray-700">Error Type</label>
                <div className="relative">
                  <select 
                    className="w-full appearance-none bg-white border border-gray-300 text-gray-700 rounded-xl py-3 px-4 pr-10 outline-none focus:ring-2 focus:ring-violet-500 focus:border-violet-500 transition shadow-sm cursor-pointer hover:bg-gray-50"
                    value={errorType}
                    onChange={(e) => setErrorType(e.target.value)}
                  >
                    <option value="Logical Error">Logical Error</option>
                    <option value="Factual Error">Factual Error</option>
                    <option value="AI Hallucination">AI Hallucination</option>
                  </select>
                  <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-4 text-gray-500">
                    <CaretDown weight="fill" size={18} />
                  </div>
                </div>
              </div>

              <div className="flex flex-col gap-2 flex-grow">
                <label className="text-sm font-semibold text-gray-700">Correction Reason</label>
                <textarea 
                  placeholder="Please enter your correction reason or the factual knowledge..."
                  className="w-full h-32 bg-white border border-gray-300 rounded-xl p-3 outline-none focus:ring-2 focus:ring-violet-500 focus:border-violet-500 resize-none transition shadow-sm"
                  value={annotation}
                  onChange={(e) => setAnnotation(e.target.value)}
                ></textarea>
              </div>

              <button 
                onClick={handleSubmit}
                disabled={!annotation.trim()}
                className={`w-full py-3 rounded-xl font-bold text-white shadow-sm transition-all flex items-center justify-center gap-2 ${annotation.trim() ? 'bg-violet-600 hover:bg-violet-700 hover:shadow-md' : 'bg-gray-300 cursor-not-allowed'}`}
              >
                <CheckCircle size={22} />
                Submit Correction
              </button>
            </div>
          ) : resolved.includes(selectedHighlight as number) ? (
            <div className="flex flex-col items-center justify-center h-full text-center text-gray-400 gap-3">
              <div className="w-16 h-16 rounded-full bg-green-100 flex items-center justify-center text-green-500 mb-2">
                <CheckCircle weight="fill" size={36} />
              </div>
              <p className="font-medium text-gray-700">Successfully debunked this error!</p>
              <p className="text-sm">+1 Point, Great job!</p>
            </div>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-center text-gray-400 gap-4">
              <CursorText size={48} className="opacity-50" />
              <p className="font-medium text-gray-500 leading-relaxed">Select/click highlighted text on the left<br/>to start your "Debunk" task</p>
            </div>
          )}
        </aside>
      </main>
    </div>
  );
}

export default Workspace;
